---
- name: Create a file in /home/ansible
  tasks:
    - name: Ensure /home/ansible/paulatest exists
      ansible.builtin.file:
        path: /home/ansible/paulatest
        state: touch
        owner: ansible
        group: ansible
        mode: '0644'
